version: '3'
services:
  database:
    container_name: database
    image: postgres:latest
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - db.env
    ports:
      - 5432:5432
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - database
    environment:
      ADMINER_DEFAULT_SERVER: database
  business-app:
    container_name: business-app
    image: wst24365888/tsmc-careerhack-2023-c6-business-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8100:8100
    depends_on:
      - database
    env_file:
      - .env
  inventory-service:
    container_name: inventory-service
    image: wst24365888/tsmc-careerhack-2023-c6-inventory-service:latest
    restart: always
    ports:
      - 8200:8200
volumes:
  pgdata:
